# Generated by Django 5.2.2 on 2025-06-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_release_date_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=120),
            preserve_default=False,
        ),
    ]
