# Generated by Django 5.2.2 on 2025-06-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
