# Generated by Django 5.2.2 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
