# Generated by Django 5.2.2 on 2025-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Viewers',
            field=models.ManyToManyField(blank=True, null=True, to='blog.viewers'),
        ),
    ]
